# Generated by Django 5.1.2 on 2024-10-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
